create table
  public.cities (
    id bigint generated by default as identity not null,
    name text not null,
    population bigint null,
    constraint cities_pkey primary key (id)
  ) tablespace pg_default;


alter table "public"."cities" add column "asd" integer;


